### ISSUE TITLE
S3 Offloads Causes Save Issue

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/doppelme-avatars#10]
With S3 Offloads active, clicking save results in a white screen. Although the avatar is saved, and appears on the profile page, it doesn't seem to appear in the adminbar, or sidebar widgets

![2016-02-17_20-01-45](https://cloud.githubusercontent.com/assets/480667/13130354/6159eece-d5b1-11e5-9bd2-1d1b0edf2f80.png)

Prior to the S3 Offloads plugin, two avatars were created in wp-content/uploads/avatars/... One #######bpfull.png and one #######bpthumb.png. Now, the thumb is no longer being created, leaving just one avatar in the folder.

**Comment by mrjarbenne** [comment]
I was going to try to re-create this on the staging site to make sure it was S3, and not the 4.4 responsive image changes that were creating this issue, but without an admin panel I can't enter the API code on the staging server to test the plugin. Previously we had comtest.hwdsb.on.ca set up prior to losing the admin panel. Any thoughts on why this might be occurring @r-a-y?

**Comment by r-a-y** [comment]
There is no admin panel to set the Doppleme settings.  By default, we fallback to the Doppelme settings that were saved in the DB from the older Doppelme plugin.

However, for staging purposes, you can use the following defines in the `wp-content/plugins/bp-custom.php` or `wp-config.php` file :

    define( 'BP_DOPPELME_PARTNER_ID',  'XXX' );
    define( 'BP_DOPPELME_PARTNER_KEY', 'XXX' );

**Comment by mrjarbenne** [comment]
Thanks. Done. With S3 still active, I'm seeing the same behaviour as on the Production site: 
Whitescreen when saving the Doppelme on:
domain.com/members/jared/profile/change-picture/?saved=1

With S3 deactivated, we see the expected behavior, the avatar and the thumbnail are both produced, so it's definitely an issue between Doppelme and S3 uploads. S3 must be hijacking the process somewhere between creating the full size image and creating the headshot thumbnail.

**Comment by r-a-y** [comment]
What's the dev site?  comtest?  A whitescreen means that there should be some errors logged in the error log.  Are there any errors there?

I'll have to debug on the test site to find out more.

**Comment by mrjarbenne** [comment]
Staging Site: http://hwdsb.staging.boreal321.com/

Opening the log now. It's not S3, it's the Fix Image Orientation Plugin that fixed this issue: https://github.com/hwdsbcommons/HWDSB-Commons/issues/80

From this WP Ticket: https://core.trac.wordpress.org/ticket/14459#comment:34

Without this plugin, the image orientation issue returns. 

Here's the error that appears when attempting to save the avatar, regardless of whether S3 is active or not:  Fatal error: Call to undefined function wp_read_image_metadata() in /var/www/hwdsb.staging.boreal321.com/wordpress/wp-content/plugins/fix-image-orientation/fix-image-orientation.php on line 35 

I had previously deactivated it as well when I deactivated S3 to narrow down the variables, and failed to see it as a variable in and of itself.

**Comment by mrjarbenne** [comment]
I had to delete the php-errors.log file because it hadn't been looked at in a while and it was 5GB. I thought it would regenerate automatically if the file didn't exist, but I guess I'm wrong. 

I downloaded it before deleting it: https://drive.google.com/file/d/0B9yl4no9k_c2U2RLbnVLMm15TW8/view?usp=sharing

**Comment by r-a-y** [comment]
> Here's the error that appears when attempting to save the avatar, regardless of whether S3 is active or not: Fatal error: Call to undefined function wp_read_image_metadata() in /var/www/hwdsb.staging.boreal321.com/wordpress/wp-content/plugins/fix-image-orientation/fix-image-orientation.php on line 35 

I've fixed the error for the fix-image-orientation.php file.

Then, I tried activating the S3 plugins on the staging site, but the S3 plugin doesn't appear to recognize uploads by our Doppelme plugin.  Not sure if the S3 plugin supports `wp_handle_sideload()` which is what our plugin uses.

Can you send me the S3 credentials to see if the avatars are being uploaded?

**Comment by mrjarbenne** [comment]
Avatars are not being uploaded into the bucket. They don't necessarily have to. We could always serve avatars from the local server. Once we offload all the content into s3, we will certainly have the space to do so on the local server. 

If the fix allows for the thumbs to be created, and the only issue is that the avatars aren't being offloaded, then we can tackle sorting out why the avatars aren't compatible with S3 at a later date. 

https://deliciousbrains.com/wp-offload-s3/doc/compatibility-with-other-plugins/

**Comment by r-a-y** [comment]
> If the fix allows for the thumbs to be created, and the only issue is that the avatars aren't being offloaded, then we can tackle sorting out why the avatars aren't compatible with S3 at a later date.

That is the case as far as I have tested on the staging site.  Let me know if you experience the same thing.

I'll hold off on diving into the Offload S3 for now.

**Comment by mrjarbenne** [comment]
Seems to be working for me. Is the fix a tweak to the fix-orientation code. Can we go live on production? The sooner this is solved, the less people I need to tag to go save their avatar again. 

Hold off on S3. I've purchased a premium license so I can offload all content to S3. Once we start down that road, we can sort out which additional directories aren't offloading correctly.

**Comment by r-a-y** [comment]
> Is the fix a tweak to the fix-orientation code. Can we go live on production?

Yeah, you should be able to move the `fix-image-orientation.php` file to production.

**Comment by mrjarbenne** [comment]
Done.
