### ISSUE TITLE
Functionality No Longer Working

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/doppelme-avatars#12]
Despite the plugin being active, the iframe for Doppel me is no longer replacing the default avatar screen in BuddyPress. I'm not seeing any errors in the logs though. 

I'm not sure how long the issue has existed. We don't have the keys defined in wp-config, but we never had needed that. They are in the database from previous set ups. 

![2019-02-04_13-35-22](https://user-images.githubusercontent.com/480667/52230076-78dc2c00-2884-11e9-9e00-146af93e73e3.png)

**Comment by r-a-y** [comment]
I do remember a key being needed.  I'll look into this.

**Comment by mrjarbenne** [comment]
I just defined the key and partner id in wp-config, just in case that's the issue. It didn't solve it though.
