### ISSUE TITLE
Frame around iFrame

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/doppelme-avatars#4]
@r-a-y In the previous version of the plugin, the avatar creator wasn't cut off on the right when the sidebar is present. It looks as if the older version pulled the template from BP and customized it to better fit the 640px limit of the iFrame. 3 years later, the BP themes have changed considerably, so the concept works, but the implementation needs an update. 

http://www.screencast.com/t/4olVBOHtW

**Comment by r-a-y** [comment]
The problem with the older version was the hardcoded references to Twenty Thirteen.

We want this to work without reliance on one theme if we're thinking about other people using the plugin.  Or do we not care about other themes?

**Comment by r-a-y** [comment]
I took a closer look at what the older plugin was doing apart from the template change and it was relatively simple.  They wrapped the iframe around a <div> with a fixed width and height.  That seems to ensure that the iframe will not be cut off.
