### ISSUE TITLE
Gravatar Settings

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/doppelme-avatars#6]
We have a user with a Gravatar showing up (either that or they have found a means of avoiding our Doppelme set up and have uploaded a local avatar somehow). 

In this new version of the plugin, I can't locate the Setting panel. The plugin is Network Activated. It must be getting it's settings from the previous database, because there doesn't seem to be a way of updating the partner ID and toggling any settings. 

Thots @r-a-y ?

**Comment by mrjarbenne** [comment]
Upon further inspection, it isn't a gravatar, it's a locally uploaded avatar. Now that we are locally caching avatars, if users had uploaded a local avatar before we had activated Doppelme, the local avatar is being served up instead of the default grey face. 

What is the impact if I go into the wp-content/avatars/##### and just delete the two instances of the local avatar?

**Comment by r-a-y** [comment]
If you manually go to the user's "Profile > Change Profile Photo" page 
and resave the item, the purging of the existing avatar and the 
mirroring of the DoppelMe avatar should occur.

Let me know if it doesn't.  Yeah, I got to fix up the WP admin bar 
link.  Will definitely get to this today!

**Comment by mrjarbenne** [comment]
If I go to change profile picture the Doppelme  creator pops up and if I click save, it goes to a file not found 404 page on the dP iframe.

**Comment by mrjarbenne** [comment]
Live site. 

User nelliott is an example.

**Comment by r-a-y** [comment]
> User nelliott is an example.

Worked for me.  I went to  `Profile > Change Profile Photo` then clicked on the `Remove DoppelMe` link located at the bottom of the page.  This removed the uploaded avatar, but also purged the the user's DoppelMe settings.  I added some customizations just so the photo isn't bare, but feel free to edit the user's DoppelMe settings some more.

**Comment by mrjarbenne** [comment]
I forgot about that link. That said, in order to eradicate all non-Doppelme avatars, if I go into wp-content/avatars and delete anything that isn't dated 2015 (when we updated the plugin) will the plugin auto-create a new directory for the user when they eventually go in and set up their DP avatar (these instances are all from users who haven't set up their avatars since we migrated to the new plugin).

**Comment by r-a-y** [comment]
Yes it should.  You can test this yourself on Comtest by deleting your own directory `/wp-content/uploads/avatars/2/` via FTP.

**Comment by mrjarbenne** [comment]
Right. (Slaps forehead).

**Comment by mrjarbenne** [comment]
Solved.
