### ISSUE TITLE
Setting Panel

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/doppelme-avatars#8]
I can't locate the Setting panel. The plugin is Network Activated. It must be getting it's settings from the previous database, because there doesn't seem to be a way of updating the partner ID and toggling any settings. 

Now that we have changed the server, the settings may need to be tweaked. The avatar creator is not found.

**Comment by r-a-y** [comment]
There is no settings panel at the moment.  It just uses the old DoppelMe keys from the DB.

**Comment by mrjarbenne** [comment]
I'm good. Was able to whitelist the new IP from the doppelme site.
